In [12]:
pip install nba_api

Requirement already satisfied: nba_api in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (1.2.1)
Requirement already satisfied: requests in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (from nba_api) (2.28.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (from nba_api) (1.23.5)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (from requests->nba_api) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (from requests->nba_api) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (from requests->nba_api) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /Users/devintrapp/anaconda3/lib/python3.10/site-packages (from requests->nba_api) (3.4)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd
from pathlib import Path

In [15]:
# Make a reference to the comic_books_expanded.csv file path
csv_path = Path("stadiums.csv")

stadiums_df = pd.read_csv(csv_path, encoding="utf-8")

stadiums_df

                   Team League            Division        Lat        Long
0      Dallas Mavericks    NBA                West  32.790556  -96.810278
1         Orlando Magic    NBA                East  28.539167  -81.383611
2     San Antonio Spurs    NBA                West  29.426944  -98.437500
3        Denver Nuggets    NBA                West  39.748920 -105.008400
4         Brooklyn Nets    NBA                East  40.682661  -73.975225
..                  ...    ...                 ...        ...         ...
146     Chicago Fire FC    MLS  Eastern Conference  41.862300  -87.616700
147  Philadelphia Union    MLS  Eastern Conference  39.832222  -75.378889
148           FC Dallas    MLS  Western Conference  33.154444  -96.835278
149       FC Cincinnati    MLS  Eastern Conference  39.111389  -84.522222
150    New York City FC    MLS  Eastern Conference  40.829167  -73.926389

[151 rows x 5 columns]

In [22]:
NBA_stadiums = stadiums_df.loc[stadiums_df["League"] == "NBA"]

NBA_stadiums

                      Team League Division        Lat        Long
0         Dallas Mavericks    NBA     West  32.790556  -96.810278
1            Orlando Magic    NBA     East  28.539167  -81.383611
2        San Antonio Spurs    NBA     West  29.426944  -98.437500
3           Denver Nuggets    NBA     West  39.748920 -105.008400
4            Brooklyn Nets    NBA     East  40.682661  -73.975225
5       Washington Wizards    NBA     East  38.898200  -77.020900
6    Golden State Warriors    NBA     West  37.768056 -122.387500
7     Los Angeles Clippers    NBA     West  34.043056 -118.267222
8       Los Angeles Lakers    NBA     West  34.043056 -118.267222
9        Memphis Grizzlies    NBA     West  35.138333  -90.050556
10         Milwaukee Bucks    NBA     East  43.045028  -87.918167
11            Phoenix Suns    NBA     West  33.445833 -112.071389
12              Miami Heat    NBA     East  25.781389  -80.188056
13          Indiana Pacers    NBA     East  39.763889  -86.155556
14        Sacremento Kings    NBA     West  38.580361 -121.499611
15         Detroit Pistons    NBA     East  42.341111  -83.055000
16         New York Knicks    NBA     East  40.750556  -73.993611
17  Portland Trail Blazers    NBA     West  45.531667 -122.666667
18   Oklahoma City Thunder    NBA     West  35.463333  -97.515000
19     Cleveland Cavaliers    NBA     East  41.496389  -81.688056
20         Toronto Raptors    NBA     East  43.643333  -79.379167
21    New Orleans Pelicans    NBA     West  29.948889  -90.081944
22       Charlotte Hornets    NBA     East  35.225000  -80.839167
23           Atlanta Hawks    NBA     East  33.757222  -84.396389
24  Minnesota Timberwolves    NBA     West  44.979500  -93.276100
25          Boston Celtics    NBA     East  42.366303  -71.062228
26         Houston Rockets    NBA     West  29.750833  -95.362222
27           Chicago Bulls    NBA     East  41.880556  -87.674167
28               Utah Jazz    NBA     West  40.768333 -111.901111
29      Philadelphia 76ers    NBA     East  39.901111  -75.171944

In [23]:
NBA_stadiums.to_csv("NBAstadiums.csv",index = False)

# CONVERT DF TO JSON

In [47]:
json_data = NBA_stadiums.to_json(orient='records')

In [38]:
csv_path = Path("teams_info.csv")

teams_df = pd.read_csv(csv_path, encoding="utf-8")

teams_df

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends
5,0,1610612743,1976,2019,DEN,Nuggets,1976,Denver,Pepsi Center,19099.0,Stan Kroenke,Tim Connelly,Michael Malone,No Affiliate
6,0,1610612745,1967,2019,HOU,Rockets,1967,Houston,Toyota Center,18104.0,Tilman Fertitta,Daryl Morey,Mike D'Antoni,Rio Grande Valley Vipers
7,0,1610612746,1970,2019,LAC,Clippers,1970,Los Angeles,Staples Center,19060.0,Steve Ballmer,Michael Winger,Doc Rivers,Agua Caliente Clippers of Ontario
8,0,1610612747,1948,2019,LAL,Lakers,1948,Los Angeles,Staples Center,19060.0,Jerry Buss Family Trust,Rob Pelinka,Frank Vogel,South Bay Lakers
9,0,1610612748,1988,2019,MIA,Heat,1988,Miami,AmericanAirlines Arena,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce
10,0,1610612749,1968,2019,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500.0,Wesley Edens &Â Marc Lasry,Jon Horst,Mike Budenholzer,Wisconsin Herd
11,0,1610612750,1989,2019,MIN,Timberwolves,1989,Minnesota,Target Center,19356.0,Glen Taylor,Scott Layden,Ryan Saunders,Iowa Wolves
12,0,1610612751,1976,2019,BKN,Nets,1976,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Kenny Atkinson,Long Island Nets
13,0,1610612752,1946,2019,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Cablevision (James Dolan),Steve Mills,David Fizdale,Westchester Knicks
14,0,1610612753,1989,2019,ORL,Magic,1989,Orlando,Amway Center,0.0,Rick DeVos,John Hammond,Steve Clifford,Lakeland Magic
15,0,1610612754,1976,2019,IND,Pacers,1976,Indiana,Bankers Life Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Nate McMillan,Fort Wayne Mad Ants
16,0,1610612755,1949,2019,PHI,76ers,1949,Philadelphia,Wells Fargo Center,NaN,Joshua Harris,Elton Brand,Brett Brown,Delaware Blue Coats
17,0,1610612756,1968,2019,PHX,Suns,1968,Phoenix,Talking Stick Resort Arena,NaN,Robert Sarver,James Jones,Monty Williams,Northern Arizona Suns
18,0,1610612757,1970,2019,POR,Trail Blazers,1970,Portland,Moda Center,19980.0,Paul Allen,Neil Olshey,Terry Stotts,No Affiliate
19,0,1610612758,1948,2019,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
20,0,1610612759,1976,2019,SAS,Spurs,1976,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs
21,0,1610612760,1967,2019,OKC,Thunder,1967,Oklahoma City,Chesapeake Energy Arena,19163.0,Clay Bennett,Sam Presti,Billy Donovan,Oklahoma City Blue
22,0,1610612761,1995,2019,TOR,Raptors,1995,Toronto,Scotiabank Arena,19800.0,Maple Leaf Sports and Entertainment,Masai Ujiri,Nick Nurse,Raptors 905
23,0,1610612762,1974,2019,UTA,Jazz,1974,Utah,Vivint Smart Home Arena,20148.0,Greg Miller,Dennis Lindsey,Quin Snyder,Salt Lake City Stars
24,0,1610612763,1995,2019,MEM,Grizzlies,1995,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle
25,0,1610612764,1961,2019,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
26,0,1610612765,1948,2019,DET,Pistons,1948,Detroit,Little Caesars Arena,21000.0,Tom Gores,Ed Stefanski,Dwane Casey,Grand Rapids Drive
27,0,1610612766,1988,2019,CHA,Hornets,1988,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,James Borrego,Greensboro Swarm
28,0,1610612739,1970,2019,CLE,Cavaliers,1970,Cleveland,Quicken Loans Arena,20562.0,Dan Gilbert,Koby Altman,John Beilein,Canton Charge
29,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors

In [46]:
team_merge = pd.merge(teams_df, ranking_df, on = 'TEAM_ID')

team_merge

,LEAGUE_ID_x,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,...,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,2022-12-22,East,Atlanta,32,16,16,0.500,10-6,6-10,NaN
1,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,2022-12-21,East,Atlanta,32,16,16,0.500,10-6,6-10,NaN
2,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,2022-12-20,East,Atlanta,31,16,15,0.516,10-5,6-10,NaN
3,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,2022-12-19,East,Atlanta,31,16,15,0.516,10-5,6-10,NaN
4,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,2022-12-18,East,Atlanta,30,15,15,0.500,9-5,6-10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,2014-09-05,West,Golden State,82,51,31,0.622,27-14,24-17,NaN
210338,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,2014-09-04,West,Golden State,82,51,31,0.622,27-14,24-17,NaN
210339,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,2014-09-03,West,Golden State,82,51,31,0.622,27-14,24-17,NaN
210340,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,2014-09-02,West,Golden State,82,51,31,0.622,27-14,24-17,NaN
210341,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,2014-09-01,West,Golden State,82,51,31,0.622,27-14,24-17,NaN

In [40]:
csv_path = Path("ranking.csv")

ranking_df = pd.read_csv(csv_path, encoding="utf-8")

ranking_df

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
210338,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
210339,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
210340,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
210341,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

In [37]:
from nba_api.stats.static import players
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
print('Number of players fetched: {}'.format(len(nba_players)))
nba_players[:30]

Number of players fetched: 4815

[{'id': 76001,
  'full_name': 'Alaa Abdelnaby',
  'first_name': 'Alaa',
  'last_name': 'Abdelnaby',
  'is_active': False},
 {'id': 76002,
  'full_name': 'Zaid Abdul-Aziz',
  'first_name': 'Zaid',
  'last_name': 'Abdul-Aziz',
  'is_active': False},
 {'id': 76003,
  'full_name': 'Kareem Abdul-Jabbar',
  'first_name': 'Kareem',
  'last_name': 'Abdul-Jabbar',
  'is_active': False},
 {'id': 51,
  'full_name': 'Mahmoud Abdul-Rauf',
  'first_name': 'Mahmoud',
  'last_name': 'Abdul-Rauf',
  'is_active': False},
 {'id': 1505,
  'full_name': 'Tariq Abdul-Wahad',
  'first_name': 'Tariq',
  'last_name': 'Abdul-Wahad',
  'is_active': False},
 {'id': 949,
  'full_name': 'Shareef Abdur-Rahim',
  'first_name': 'Shareef',
  'last_name': 'Abdur-Rahim',
  'is_active': False},
 {'id': 76005,
  'full_name': 'Tom Abernethy',
  'first_name': 'Tom',
  'last_name': 'Abernethy',
  'is_active': False},
 {'id': 76006,
  'full_name': 'Forest Able',
  'first_name': 'Forest',
  'last_name': 'Able',
  'is_active': False},
 {'id': 76007,
  'full_name': 'John Abramovic',
  'first_name': 'John',
  'last_name': 'Abramovic',
  'is_active': False},
 {'id': 203518,
  'full_name': 'Alex Abrines',
  'first_name': 'Alex',
  'last_name': 'Abrines',
  'is_active': False},
 {'id': 1630173,
  'full_name': 'Precious Achiuwa',
  'first_name': 'Precious',
  'last_name': 'Achiuwa',
  'is_active': True},
 {'id': 101165,
  'full_name': 'Alex Acker',
  'first_name': 'Alex',
  'last_name': 'Acker',
  'is_active': False},
 {'id': 76008,
  'full_name': 'Donald Ackerman',
  'first_name': 'Donald',
  'last_name': 'Ackerman',
  'is_active': False},
 {'id': 76009,
  'full_name': 'Mark Acres',
  'first_name': 'Mark',
  'last_name': 'Acres',
  'is_active': False},
 {'id': 76010,
  'full_name': 'Charles Acton',
  'first_name': 'Charles',
  'last_name': 'Acton',
  'is_active': False},
 {'id': 203112,
  'full_name': 'Quincy Acy',
  'first_name': 'Quincy',
  'last_name': 'Acy',
  'is_active': False},
 {'id': 76011,
  'full_name': 'Alvan Adams',
  'first_name': 'Alvan',
  'last_name': 'Adams',
  'is_active': False},
 {'id': 76012,
  'full_name': 'Don Adams',
  'first_name': 'Don',
  'last_name': 'Adams',
  'is_active': False},
 {'id': 200801,
  'full_name': 'Hassan Adams',
  'first_name': 'Hassan',
  'last_name': 'Adams',
  'is_active': False},
 {'id': 1629121,
  'full_name': 'Jaylen Adams',
  'first_name': 'Jaylen',
  'last_name': 'Adams',
  'is_active': False},
 {'id': 203919,
  'full_name': 'Jordan Adams',
  'first_name': 'Jordan',
  'last_name': 'Adams',
  'is_active': False},
 {'id': 149,
  'full_name': 'Michael Adams',
  'first_name': 'Michael',
  'last_name': 'Adams',
  'is_active': False},
 {'id': 203500,
  'full_name': 'Steven Adams',
  'first_name': 'Steven',
  'last_name': 'Adams',
  'is_active': True},
 {'id': 912,
  'full_name': 'Rafael Addison',
  'first_name': 'Rafael',
  'last_name': 'Addison',
  'is_active': False},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo',
  'is_active': True},
 {'id': 1629061,
  'full_name': 'Deng Adel',
  'first_name': 'Deng',
  'last_name': 'Adel',
  'is_active': False},
 {'id': 76015,
  'full_name': 'Rick Adelman',
  'first_name': 'Rick',
  'last_name': 'Adelman',
  'is_active': False},
 {'id': 202399,
  'full_name': 'Jeff Adrien',
  'first_name': 'Jeff',
  'last_name': 'Adrien',
  'is_active': False},
 {'id': 201167,
  'full_name': 'Arron Afflalo',
  'first_name': 'Arron',
  'last_name': 'Afflalo',
  'is_active': False},
 {'id': 1630534,
  'full_name': 'Ochai Agbaji',
  'first_name': 'Ochai',
  'last_name': 'Agbaji',
  'is_active': True}]

In [2]:
from nba_api.stats.static import teams, players
from nba_api.stats.endpoints import cumestatsteamgames, cumestatsteam, gamerotation
import pandas as pd
import numpy as np
import json
import difflib
import time
import requests

In [3]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203076,2012-13,00,1610612740,NOH,20.0,64,60,1846.0,349,...,0.751,165,357,522,63,75,112,89,158,867
1,203076,2013-14,00,1610612740,NOP,21.0,67,66,2358.0,522,...,0.791,207,466,673,105,89,189,109,200,1394
2,203076,2014-15,00,1610612740,NOP,22.0,68,68,2455.0,642,...,0.805,173,523,696,149,100,200,95,141,1656
3,203076,2015-16,00,1610612740,NOP,23.0,61,61,2164.0,560,...,0.758,130,497,627,116,78,125,121,148,1481
4,203076,2016-17,00,1610612740,NOP,24.0,75,75,2708.0,770,...,0.802,172,712,884,157,94,167,181,168,2099
5,203076,2017-18,00,1610612740,NOP,25.0,75,75,2727.0,780,...,0.828,187,644,831,174,115,193,162,159,2110
6,203076,2018-19,00,1610612740,NOP,26.0,56,56,1850.0,530,...,0.794,174,498,672,218,88,135,112,132,1452
7,203076,2019-20,00,1610612747,LAL,27.0,62,62,2131.0,551,...,0.846,142,435,577,200,91,143,154,156,1618
8,203076,2020-21,00,1610612747,LAL,28.0,36,36,1162.0,301,...,0.738,62,224,286,110,45,59,74,60,786
9,203076,2021-22,00,1610612747,LAL,29.0,40,40,1404.0,370,...,0.713,106,288,394,122,49,90,82,97,927
10,203076,2022-23,00,1610612747,LAL,30.0,56,54,1905.0,542,...,0.784,195,507,702,148,59,114,122,146,1451

In [35]:
from nba_api.stats.endpoints import TeamYearByYearStats

data = TeamYearByYearStats.TeamYearByYearStats
data.get_data_frames()[0]

AttributeError: type object 'TeamYearByYearStats' has no attribute 'TeamYearByYearStats'

In [25]:
from nba_api.stats.static import teams
# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
print('Number of teams fetched: {}'.format(len(nba_teams)))
nba_teams[:30]

Number of teams fetched: 30

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]